spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/PracticoFinal?createDatabaseIfNotExist=true
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver